

data_info_dict = {
    'MAYO': {'data_path': '/data/brainnet/public_dataset/MAYO/group_data_15000_2to0/',
        'group_num': 6,
        'split': [3, 1, 2],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
        },
    'FNUSA': {'data_path': '/data/brainnet/public_dataset/FNUSA/group_data_15000_2to0/',
        'group_num': 6,
        'split': [3, 1, 2],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
        },
    'CHBMIT': {'data_path': '/data/brainnet/physio_signal_dataset/CHB_MIT/files/chbmit/1.0.0/group_data/',
        'group_num': 4,
        'split': [2, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
        },
    'Siena': {'data_path': '/data/brainnet/physio_signal_dataset/Siena/physionet.org/files/siena-scalp-eeg/1.0.0/group_data/',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
        },

    'Clinical': {'sampled_data_path': '/data/brainnet/SEEG_npy/sampled_data/seizure_detection',
        'unsampled_data_path': '/data/brainnet/SEEG_edf',
        'group_num': 4,
        'split': [2, 1, 1],
        'various_ch_num': True,    # cannot merge to one file
        'n_class': 2,
        'label_level': 'channel_level',    # y: (bsz, ch_num,) instead of (bsz,)
        },

    'SleepEDFx': {
        'data_path': '/data/brainnet/physio_signal_dataset/SleepEDFx_dataset/tinysleepnet_data/eeg_fpz_cz/group_data/',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 5,
        'label_level': 'subject_level',
        },
    'HMC': {
        'data_path': '/data/brainnet/physio_signal_dataset/HMC_dataset/physionet.org/files/hmc-sleep-staging/1.1/npy_data/group_data/',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 5,
        'label_level': 'subject_level',
        },
    'SeizureA': {'data_path': '/data/brainnet/physio_signal_dataset/SeizureA_ts/preprocess_and_segment/group_data/',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
    },
    'SeizureC': {'data_path': '/data/brainnet/physio_signal_dataset/SeizureC_ts/preprocess_and_segment/group_data/',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
    },
    'SeizureB': {'data_path': '/data/brainnet/physio_signal_dataset/SeizureB_ts/preprocess_and_segment/group_data/',
        'group_num': 6,
        'split': [4, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
    },
    'RepOD': {'data_path': '/data/brainnet/public_dataset/RepOD/group_data/',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
    },
    'UCSD_ON': {'data_path': '/data/brainnet/public_dataset/UCSD_Parkinson/on/',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
    },
    'UCSD_OFF': {'data_path': '/data/brainnet/public_dataset/UCSD_Parkinson/off/',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
    },
    'HUSM': {'data_path': '/data/brainnet/public_dataset/HUSM/group_data/',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
    },
    'ISRUC': {'data_path': '/data/brainnet/physio_signal_dataset/ISRUC_dataset/group_data/',
        'group_num': 4,
        'split': [2, 1, 1],
        'various_ch_num': False,
        'n_class': 5,
        'label_level': 'subject_level',
    },
}
