
# To effectively avoid the risk of data leakage, this benchmark adopts a cross-subject grouping strategy.
data_info_dict = {
    'MAYO': {'data_path': '',
        'group_num': 6,
        'split': [3, 1, 2],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
        },
    'FNUSA': {'data_path': '',
        'group_num': 6,
        'split': [3, 1, 2],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
        },
    'CHBMIT': {'data_path': '',
        'group_num': 4,
        'split': [2, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
        },
    'Siena': {'data_path': '',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
        },

    'Clinical': {'sampled_data_path': '',
        'unsampled_data_path': '',
        'group_num': 4,
        'split': [2, 1, 1],
        'various_ch_num': True,    # cannot merge to one file
        'n_class': 2,
        'label_level': 'channel_level',    # y: (bsz, ch_num,) instead of (bsz,)
        },

    'SleepEDFx': {
        'data_path': '',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 5,
        'label_level': 'subject_level',
        },
    'HMC': {
        'data_path': '',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 5,
        'label_level': 'subject_level',
        },
    'SeizureA': {'data_path': '',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
    },
    'SeizureC': {'data_path': '',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
    },
    'SeizureB': {'data_path': '',
        'group_num': 6,
        'split': [4, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
    },
    'RepOD': {'data_path': '',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
    },
    'UCSD_ON': {'data_path': '',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
    },
    'UCSD_OFF': {'data_path': '',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
    },
    'HUSM': {'data_path': '',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'label_level': 'subject_level',
    },
    'ISRUC': {'data_path': '',
        'group_num': 4,
        'split': [2, 1, 1],
        'various_ch_num': False,
        'n_class': 5,
        'label_level': 'subject_level',
    },
}
